CREATE DATABASE bai2;
use bai2;
CREATE TABLE trainee (
    trainee_ID INT PRIMARY KEY AUTO_INCREMENT,
    FULL_NAME NVARCHAR(255),
    BIRTH_DATE DATE,
    GENDER ENUM('Male', 'Female', 'UNKNOWN'),
    ET_IQ TINYINT,
    CHECK (0 <= ET_IQ <= 20),
    ET_GMATH TINYINT,
    CHECK (0 <= ET_GMATH <= 20),
    ET_ENGLISH TINYINT,
    CHECK (0 <= ET_ENGLISH <= 50),
    TRAINING_CLASS VARCHAR(255),
    EVALUATION_NOTES TEXT
);



